spring.application.name=javahandbook

spring.datasource.url=jdbc:mysql://localhost:3306/java_handbook_db?useSSL=false&serverTimezone=Europe/Kyiv&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root

app.admin.username=admin
app.admin.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false

# Mail settings
spring.mail.host=smtp.ukr.net
spring.mail.port=465
spring.mail.username=javahandbook@ukr.net
spring.mail.password=MZJGvNesnYsDo8j3
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
#spring.mail.properties.mail.debug=true

# Site settings
app.site.base-url=http://localhost:8080

# Notifications
app.notifications.admin-email=javahandbook@ukr.net
app.notifications.from-email=javahandbook@ukr.net

#logging.level.org.springframework.mail=DEBUG
